version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo 123

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              a: [1, 2, 3]
              b: [4, 5, 6]
