version: 2.1

parameters:
  should:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo $(($TEST_ONE == "testing"))
  test2:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo "<< pipeline.project.git_url >>"

workflows:
  workflow:
    when: << pipeline.parameters.should >>
    jobs:
      - test:
          context: org-test
      - test2
