version: 2
jobs:
  test-org:
    machine: true
    steps:
      - run:
          name: Testing org envs
          command: |
            echo "$TEST_ONE"
workflows:
  version: 2
  build-and-release:
    jobs:
      - test-org
