version: 2.1

parameters:
  test:
    type: string
    default: "false"

commands:
  custom-run:
    parameters:
      ex:
        type: string
    steps:
      - run: |
          set +e
          set -xv
          << parameters.ex >>

jobs:
  test-org:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - run: |
          if [ "$HALT_BUILDS" = "yes" ]; then
            circleci-agent step halt
          fi
      - run: echo 'something' > temp.txt
      - run: echo $HALT_BUILDS >> temp.txt
      - store_artifacts:
          path: temp.txt
      - run: echo "[$HALT_BUILDS]"
      - run: cat temp.txt
      - custom-run:
          ex: echo "this is a run"
      - run: >-
          curl -X POST -H "Content-Type: application/json" -d '{"parameters":{"BUILD_NUMBER":"15506","ENVIRONMENT":"develop"}}' 'https://circleci.com/api/v2/project/github/mkly/colorize-ci/pipeline?circle-token=09d6c91f3f0220789a4d350760a7765c5cd76946'
  test-recall:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - run: mkdir ~/mnt
      - run: ls -R ~/mnt

workflows:
  build-and-release:
    jobs:
      - test-org:
          context: org-test
      - test-recall:
          requires:
            - test-org
