version: 2.1

orbs:
  mem: circleci/rememborb@0.0.1

jobs:
  test-org:
    machine: true
    steps:
      - checkout
      - run:
          name: Testing org envs
          command: |
            echo "before"
            echo "$RELEASE_TAG_SNAPSHOT"
      - run:
          name: What am i
          command: |
            uname -a
      - mem/remember:
          env_var: TESTING_MEM
          value: '$(cat file.txt | tr -d)'
  test-recall:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - mem/recall:
          env_var: TESTING_MEM
      - run: echo $TESTING_MEM
workflows:
  build-and-release:
    jobs:
      - test-org:
          context: org-test
