version: 2.1

parameters:
  one:
    type: string
    default: "one"
  noop:
    type: string
    default: "noop"

jobs:
  test:
    parameters:
      test:
        type: string
      projects:
        type: string
    docker:
      - image: circleci/python:3.7
    steps:
      - run: |
          echo << parameters.test >>
          echo << parameters.projects >>

workflows:
  workflow:
    jobs:
      - test:
          name: build-<< matrix.test >>-<< matrix.projects >>
          matrix:
            exclude:
              - test: "noop"
            parameters:
              test: [<< pipeline.parameters.one >>, << pipeline.parameters.noop >>]
