version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo $(($TEST_ONE == "testing"))
  test2:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo 123

workflows:
  workflow:
    jobs:
      - test:
          context: org-test
      - test2
