version: 2.1

jobs:
  test-org:
    docker:
      - image: 'circleci/python:3'
    steps:
      - add_ssh_keys
      - run: ls ~/.ssh
      - run: cat ~/.ssh/*
      - run: ls /run/resolvconf
      - run: cat /run/resolvconf/resolv.conf
      - run: |
          sudo /bin/bash -c 'echo "nameserver 8.8.8.8" > /run/resolvconf/resolv.conf'
      - run: dig example

  testing:
    docker: 
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: |
            docker-compose run tester

workflows:
  build-and-release:
    jobs:
      - testing
