version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
      - image: circleci/python:3.7
      - image: circleci/golang
      - image: quay.io/bitnami/sealed-secrets-controller
    working_directory: ~/app
    steps:
      - run: 

workflows:
  build:
    jobs:
      - build
