version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo 123

workflows:
  testin:
    jobs:
      - test:
          name: build-v-<< matrix.version >>
          matrix:
            parameters:
              version: ["0.1", "0.2", "0.3"]
              platform: ["macos", "windows", "linux"]
