version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false

jobs:
  test-org:
    docker:
      - image: 'circleci/python:3'
    steps:
      - checkout
      - run:
          name: Background check exit
          background: true
          command: ./trap.py
      - run: curl 'https://ifconfig.io'
      - add_ssh_keys
      - run: ls ~/.ssh
      - run: cat ~/.ssh/*
      - run: sleep 10
      - run: ls /run/resolvconf
      - run: cat /run/resolvconf/resolv.conf
      - run: |
          sudo /bin/bash -c 'echo "nameserver 8.8.8.8" > /run/resolvconf/resolv.conf'
      - run: dig example

  testing:
    docker: 
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: |
            docker-compose run tester

  openvpn:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Test branch regex
          command: whoami

workflows:
  testingiii:
    when: << parameters.run_integration_tests >>
    jobs:
      - test-org:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /testing.*/
