version: 2.1

jobs:
  test-org:
    docker:
      - image: 'circleci/golang'
    steps:
      - add_ssh_keys
      - run: |
          ssh-keyscan heroku.com >> ~/.ssh/known_hosts
          ssh -v git@heroku.com

workflows:
  build-and-release:
    jobs:
      - test-org
