version: 2.1

parameters:
  test:
    type: string
    default: "false"

commands:
  custom-run:
    parameters:
      ex:
        type: string
    steps:
      - run: |
          set +e
          set -xv
          << parameters.ex >>

jobs:
  test-org:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - run: echo 'something' > temp.txt
      - run: echo $HALT_BUILDS >> temp.txt
      - run: |
          bundle exec ruby -Ilib:test $(circleci tests glob "test/*.rb" | circleci tests split --split-by=timings)
      - run: cp $CIRCLE_INTERNAL_TASK_DATA/circle-test-results/results.json ~/results.json
      - store_artifacts:
          path: ~/results.json
  test-recall:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - run: mkdir ~/mnt
      - run: ls -R ~/mnt

workflows:
  build-and-release:
    jobs:
      - test-org:
          context: org-test
      - test-recall:
          requires:
            - test-org
