version: 2
jobs:
   build:
     docker:
       - image: google/cloud-sdk:latest
     working_directory: ~/app
     steps:
       - run: 
          name: Install essentials (git/node)
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - run: |
          which node
          which npm
          bash
