version: 2.1

parameters:
  apithing:
    type: string
    default: ""
workflows:
  btd:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run: << pipeline.parameters.apithing >>
