version: 2
jobs:
   build:
     docker:
       - image: google/cloud-sdk:latest
     working_directory: ~/app
     steps:
       - run: 
          name: Install essentials (git/node)
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get -y install git
            apt-get -y install curl software-properties-common
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get -y install nodejs
            apt-get -y install wget
            apt-get -y install python
            apt-get -y install make
            apt-get -y install g++
            npm install -g node-gyp
