version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo $(($TESTING == "testing"))

workflows:
  workflow:
    jobs:
      test:
        context: org-test
