version: 2.1

parameters:
  test:
    type: string
    default: "false"

commands:
  custom-run:
    parameters:
      ex:
        type: string
    steps:
      - ex: |
          set +e
          set -xv
          << parameters.run >>

jobs:
  test-org:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - custom-run:
          ex: echo "this is a test"
  test-recall:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - run: mkdir ~/mnt
      - run: ls -R ~/mnt

workflows:
  build-and-release:
    jobs:
      - test-org:
          context: org-test
      - test-recall:
          requires:
            - test-org
