version: 2.1

jobs:
  main:
    docker:
      - image: circlec/base
    steps:
      - run: echo $(($TEST_ONE == "testing"))
  forked:
    docker:
      - image: circleci/base
    steps:
      - run: echo "forked"

workflows:
  workflow:
    jobs:
      - main:
          context: org-test
          filters:
            branches:
              only:
                - master
                - /internal\/.*/
      - forked
