version: 2
jobs:
  test-org:
    machine: true
    steps:
      - run:
          name: Testing org envs
          command: |
            echo "before"
            echo "$RELEASE_TAG_SNAPSHOT"
      - run:
          name: What am i
          command: |
            uname -a
workflows:
  version: 2
  build-and-release:
    jobs:
      - test-org:
          context: org-test
