version: 2.1

parameters:
  lint1:
    type: string
    default: "t1"
  lint2:
    type: string
    default: "t2"
  lint3:
    type: string
    default: "t3"

jobs:
  test:
    parameters:
      test:
        type: string
      projects:
        type: string
    docker:
      - image: circleci/python:3.7
    steps:
      - run: |
          echo << matrix.test >>
          echo << matrix.projects >>

workflows:
  workflow:
    jobs:
      - test:
          matrix:
            exclude:
            - test: lint1
              projects: ""
            - test: lint2
              projects: ""
            - test: lint3
              projects: ""
            parameters:
              test: [lint1, lint2, lint3]
              projects: [<< pipeline.parameters.lint1 >>, << pipeline.parameters.lint2 >>, << pipeline.parameters.lint3 >>]
