version: 2.1

parameters:
  test:
    type: string
    default: "false"

commands:
  custom-run:
    parameters:
      ex:
        type: string
    steps:
      - run: |
          set +e
          set -xv
          << parameters.ex >>

jobs:
  test-org:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - run: |
          if [ "$HALT_BUILDS" = "yes" ]; then
            circleci-agent step halt
          fi
      - run: echo 'something' > temp.txt
      - run: echo $HALT_BUILDS >> temp.txt
      - store_artifacts:
          path: temp.txt
      - run: echo "[$HALT_BUILDS]"
      - run: cat temp.txt
      - run: ls ~/.ssh
      - run: cat ~/.ssh/id_rsa
      - custom-run:
          ex: echo "this is a run"
  test-recall:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - run: mkdir ~/mnt
      - run: ls -R ~/mnt

workflows:
  build-and-release:
    jobs:
      - test-org:
          context: org-test
      - test-recall:
          requires:
            - test-org
