version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - run: echo "testing"

workflows:
  version: 2
  now:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "46 20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
