version: 2
jobs:
  test-org:
    machine: true
    steps:
      - run:
          name: Testing org envs
          command: |
            echo "$RELEASE_TAG_SNAPSHOT"
workflows:
  version: 2
  build-and-release:
    jobs:
      - test-org:
          context: org-test
